const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const tr={
 en:{hub:'Enterprise Hub',home:'Home',explorer:'Equipment Explorer',map:'Knowledge Map',library:'Library',academy:'Academy',admin:'Admin',progress:'Progress',challenge:'Challenges',ai:'Ask FALTAH',overline:'Digital Technical Academy',heroTitle:'The company technical brain — now with academy, progress, challenges and AI-ready search.',heroText:'Explore equipment, understand how it works, follow learning journeys, complete challenges, and ask FALTAH for guidance.',openExplorer:'Open Equipment Explorer',askFaltah:'Ask FALTAH',equipmentItems:'Equipment Items',lessons:'Lessons',completion:'Completion',ready:'Ready Architecture',todays:"Today's Knowledge",viewAll:'View All',quickModules:'Quick Modules',continueLearning:'Continue Learning',explorerText:'Select a discipline, then open equipment details, components, failures, troubleshooting and knowledge films.',mapText:'A simplified process flow where every equipment is clickable.',libraryText:'Videos, lessons, manuals, troubleshooting and case studies.',academyText:'Structured journeys for new operators, senior operators, troubleshooting, and technical leadership.',progressText:'Track completed lessons, badges, certificates, and learning hours.',challengeText:'Weekly micro challenges to build knowledge and engagement.',aiText:'Prototype assistant. In the future, this connects to Azure AI and approved knowledge documents.',adminLogin:'Admin Login',overview:'Overview',components:'Components',principle:'Operating Principle',failures:'Common Failures',troubleshooting:'Troubleshooting',maintenance:'Maintenance',films:'Knowledge Films',documents:'Documents',quiz:'Quiz',ask:'Ask FALTAH Coming Soon',resources:'Resources'},
 ar:{hub:'المنصة المؤسسية',home:'الرئيسية',explorer:'مستكشف المعدات',map:'خريطة المعرفة',library:'المكتبة',academy:'الأكاديمية',admin:'المشرف',progress:'التقدم',challenge:'التحديات',ai:'اسأل فلته',overline:'الأكاديمية الفنية الرقمية',heroTitle:'العقل الفني للشركة — الآن مع الأكاديمية والتقدم والتحديات وبحث جاهز للذكاء الاصطناعي.',heroText:'استكشف المعدات وافهم طريقة عملها واتبع مسارات التعلم وأكمل التحديات واسأل فلته للإرشاد.',openExplorer:'افتح مستكشف المعدات',askFaltah:'اسأل فلته',equipmentItems:'المعدات',lessons:'الدروس',completion:'الإنجاز',ready:'جاهزية الذكاء',todays:'معرفة اليوم',viewAll:'عرض الكل',quickModules:'وحدات سريعة',continueLearning:'متابعة التعلم',explorerText:'اختر التخصص ثم افتح تفاصيل المعدات والمكونات والأعطال واستكشاف المشاكل والأفلام الفنية.',mapText:'مخطط مبسط للعملية، كل معدة قابلة للفتح.',libraryText:'فيديوهات ودروس وأدلة واستكشاف مشاكل ودراسات حالة.',academyText:'مسارات منظمة للمشغلين الجدد وكبار المشغلين واستكشاف المشاكل والقيادة الفنية.',progressText:'تابع الدروس المكتملة والشارات والشهادات وساعات التعلم.',challengeText:'تحديات أسبوعية قصيرة لتعزيز المعرفة والتفاعل.',aiText:'مساعد تجريبي. مستقبلاً سيتم ربطه مع Azure AI والمستندات المعتمدة.',adminLogin:'دخول المشرف',overview:'نظرة عامة',components:'المكونات',principle:'مبدأ التشغيل',failures:'الأعطال الشائعة',troubleshooting:'استكشاف المشاكل',maintenance:'الصيانة',films:'الأفلام الفنية',documents:'الوثائق',quiz:'اختبار',ask:'اسأل فلته قريباً',resources:'الموارد'}
};
const disciplines=[['Process','🏭','Process Systems','أنظمة المعالجة'],['Rotating','⚙️','Rotating Equipment','المعدات الدوارة'],['Valves','🚰','Valves','الصمامات'],['Instrumentation','📈','Instrumentation','الأجهزة الدقيقة'],['Electrical','⚡','Electrical','الكهرباء'],['Safety','🔥','Safety Systems','أنظمة السلامة']];
const equipment=[
{id:'separator',discipline:'Process',icon:'🏭',name:'Three-Phase Separator',ar:'الفاصل ثلاثي الطور',overview:'Separates produced fluids into gas, oil and water using gravity, retention time and level control.',components:['Inlet diverter','Weir plate','Mist extractor','Oil level control','Water level control'],principle:'Flow enters the vessel, velocity reduces, gas rises, liquids settle, and oil/water interface is controlled.',failures:['Liquid carryover','Oil in water outlet','High pressure','Level instability'],troubleshooting:['Check inlet disturbance','Verify level instruments','Inspect pressure control','Review flow rate and retention time'],maintenance:['Inspect internals','Clean mist extractor','Calibrate level instruments','Inspect vessel corrosion']},
{id:'pump',discipline:'Rotating',icon:'⚙️',name:'Centrifugal Pump',ar:'مضخة الطرد المركزي',overview:'Converts mechanical energy into pressure and flow by rotating an impeller.',components:['Impeller','Volute casing','Shaft','Mechanical seal','Bearings'],principle:'Liquid enters the impeller eye and gains velocity before the casing converts velocity to pressure.',failures:['Cavitation','Low discharge pressure','High vibration','Seal leakage'],troubleshooting:['Check suction level','Confirm valve lineup','Verify rotation','Review NPSH and flow'],maintenance:['Lubrication','Alignment','Seal inspection','Bearing monitoring']},
{id:'compressor',discipline:'Rotating',icon:'🌀',name:'Gas Compressor',ar:'ضاغط الغاز',overview:'Raises gas pressure for processing, transfer or injection service.',components:['Rotor','Diffuser','Seal system','Bearings','Lube oil system'],principle:'Gas is accelerated and compressed through rotating and stationary elements.',failures:['Surge','High vibration','Seal gas issue','High discharge temperature'],troubleshooting:['Check anti-surge valve','Review suction conditions','Verify lube oil','Check recycle flow'],maintenance:['Vibration monitoring','Seal checks','Oil analysis','Performance testing']},
{id:'gate',discipline:'Valves',icon:'🚰',name:'Gate Valve',ar:'صمام البوابة',overview:'Used mainly for isolation service with low pressure drop when fully open.',components:['Body','Gate','Stem','Bonnet','Seat rings'],principle:'A gate moves up/down to open or block the flow path.',failures:['Passing valve','Stem damage','Seat leakage','Hard operation'],troubleshooting:['Check position','Inspect actuator/handwheel','Verify seat condition','Check for debris'],maintenance:['Lubrication','Packing adjustment','Seat inspection','Exercise valve']},
{id:'psv',discipline:'Safety',icon:'🛡️',name:'Pressure Safety Valve',ar:'صمام الأمان للضغط',overview:'Protects equipment from overpressure by relieving fluid to a safe location.',components:['Nozzle','Disc','Spring','Bonnet','Blowdown ring'],principle:'When pressure reaches set pressure, lifting force overcomes spring force and valve opens.',failures:['Leakage','Wrong set pressure','Chatter','Blocked outlet'],troubleshooting:['Check inlet/outlet isolation','Review backpressure','Inspect set pressure','Verify process conditions'],maintenance:['Bench test','Inspection','Calibration','Seal verification']},
{id:'transmitter',discipline:'Instrumentation',icon:'📈',name:'Pressure Transmitter',ar:'مرسل الضغط',overview:'Measures process pressure and sends a signal to control and monitoring systems.',components:['Sensor','Electronics','Process connection','Impulse line','Terminal block'],principle:'Pressure deflects a sensing element and electronics convert it into a standard signal.',failures:['Wrong reading','Impulse line blockage','Calibration drift','Signal loss'],troubleshooting:['Check impulse line','Verify calibration','Inspect power/signal','Compare local gauge'],maintenance:['Calibration','Impulse line flushing','Loop check','Connection inspection']},
{id:'heatx',discipline:'Process',icon:'♨️',name:'Heat Exchanger',ar:'المبادل الحراري',overview:'Transfers heat between two fluids without mixing them.',components:['Shell','Tubes','Baffles','Channel head','Tube sheet'],principle:'Heat moves from hot stream to cold stream through a conductive surface.',failures:['Fouling','Tube leak','Low heat transfer','High pressure drop'],troubleshooting:['Check temperatures','Review flow rates','Inspect fouling trend','Pressure test if leak suspected'],maintenance:['Chemical cleaning','Tube inspection','Gasket replacement','Performance monitoring']},
{id:'motor',discipline:'Electrical',icon:'⚡',name:'Electric Motor',ar:'المحرك الكهربائي',overview:'Converts electrical energy into mechanical rotation to drive equipment.',components:['Stator','Rotor','Bearings','Terminal box','Cooling fan'],principle:'Magnetic fields create torque and rotation.',failures:['Overload trip','High temperature','Bearing noise','Insulation failure'],troubleshooting:['Check load','Verify voltage/current','Inspect cooling','Check bearing condition'],maintenance:['Megger test','Lubrication','Cooling path cleaning','Alignment check']}
];
const starterResources=[
{id:'r1',eq:'pump',type:'Video',title:'Pump Working Principle',desc:'60-second explanation of how a centrifugal pump works.',url:''},
{id:'r2',eq:'pump',type:'Troubleshooting',title:'Low Discharge Pressure',desc:'Possible causes and recommended checks for low discharge pressure.',url:''},
{id:'r3',eq:'separator',type:'Video',title:'Inside a Three-Phase Separator',desc:'Visual explanation of gas, oil and water separation.',url:''},
{id:'r4',eq:'psv',type:'Video',title:'Why PSV Opens',desc:'Set pressure and overpressure protection explained simply.',url:''},
{id:'r5',eq:'gate',type:'Manual',title:'Valve Isolation Basics',desc:'Quick reference for valve isolation applications.',url:''},
{id:'r6',eq:'heatx',type:'Case Study',title:'Heat Exchanger Fouling',desc:'Symptoms and performance impact of fouling.',url:''},
{id:'r7',eq:'compressor',type:'Video',title:'Compressor Surge Explained',desc:'Simple explanation of surge, recycle and anti-surge control.',url:''},
{id:'r8',eq:'transmitter',type:'Document',title:'Pressure Transmitter Loop Check',desc:'Basic checklist for checking transmitter signal health.',url:''}
];
let state={lang:localStorage.lang||'en',theme:localStorage.theme||'dark',page:'home',disc:'Process',q:'',rq:'',rtype:'All',admin:sessionStorage.admin==='true',resources:JSON.parse(localStorage.resources_v5||'null')||starterResources,completed:JSON.parse(localStorage.completed_v5||'[]')};
const T=k=>(tr[state.lang]||tr.en)[k]||k, name=e=>state.lang==='ar'?e?.ar||e?.name:e?.name;
function save(){localStorage.resources_v5=JSON.stringify(state.resources);localStorage.completed_v5=JSON.stringify(state.completed)}
function apply(){document.documentElement.lang=state.lang;document.documentElement.dir=state.lang==='ar'?'rtl':'ltr';document.body.classList.toggle('light',state.theme==='light');$$('[data-i18n]').forEach(x=>x.textContent=T(x.dataset.i18n));$('#langBtn').textContent=state.lang==='en'?'العربية':'English';$('#themeBtn').textContent=state.theme==='light'?'☀️':'🌙';render()}
function openPage(p){state.page=p;$$('.page').forEach(x=>x.classList.toggle('active',x.id===p));$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===p));$('#pageTitle').textContent=p==='home'?'FALTAH Enterprise':T(p);scrollTo({top:0,behavior:'smooth'});render()}
function render(){
 $('#kEquipment').textContent=equipment.length; $('#kLessons').textContent=state.resources.length; const pct=Math.round((state.completed.length/Math.max(state.resources.length,1))*100); $('#kComplete').textContent=pct+'%';
 const today=state.resources[new Date().getDate()%state.resources.length] || state.resources[0]; $('#todayLesson').innerHTML=`<div><span class="pill">${today.type}</span><h2>${today.title}</h2><p>${today.desc}</p></div><button onclick="openResource('${today.id}')" class="primary">Open</button>`;
 $('#continueCards').innerHTML=equipment.slice(0,4).map(e=>`<div class="card mini" onclick="openEquipment('${e.id}')"><span>${e.icon}</span><b>${name(e)}</b><div class="progress"><i style="width:${25+e.name.length%55}%"></i></div></div>`).join('');
 $('#disciplineTabs').innerHTML=disciplines.map(d=>`<button class="tab ${state.disc===d[0]?'active':''}" data-disc="${d[0]}">${d[1]} ${state.lang==='ar'?d[3]:d[2]}</button>`).join('');
 const eqs=equipment.filter(e=>e.discipline===state.disc && name(e).toLowerCase().includes(state.q.toLowerCase()));
 $('#equipmentGrid').innerHTML=eqs.map(e=>`<article class="card equipment" onclick="openEquipment('${e.id}')"><span>${e.icon}</span><h3>${name(e)}</h3><p>${e.overview}</p><small>${state.resources.filter(r=>r.eq===e.id).length} resources</small></article>`).join('');
 $('#processMap').innerHTML=['separator','pump','heatx','gate','psv','transmitter'].map((id,i)=>{let e=equipment.find(x=>x.id===id);return `<button onclick="openEquipment('${id}')"><span>${e.icon}</span><b>${name(e)}</b></button>${i<5?'<em>→</em>':''}`}).join('');
 const types=['All','Video','Manual','Troubleshooting','Case Study','Quiz','Document']; $('#resourceTypeTabs').innerHTML=types.map(t=>`<button class="tab ${state.rtype===t?'active':''}" data-rtype="${t}">${t}</button>`).join('');
 const rs=state.resources.filter(r=>(state.rtype==='All'||r.type===state.rtype)&&(r.title+r.desc+r.type+(equipment.find(e=>e.id===r.eq)?.name||'')).toLowerCase().includes(state.rq.toLowerCase()));
 $('#libraryGrid').innerHTML=rs.map(resourceCard).join('') || '<div class="card">No resources found.</div>';
 $('#academyGrid').innerHTML=['New Operator','Rotating Equipment','Process Systems','Valve Specialist','Instrumentation','Troubleshooting'].map((p,i)=>`<div class="card path"><h3>${p}</h3><p>${20+i*11}% complete</p><div class="progress"><i style="width:${20+i*11}%"></i></div><button onclick="openPage('library')">Continue</button></div>`).join('');
 renderProgress(pct); renderAdmin();
}
function renderProgress(pct){$('#scorePercent').textContent=pct+'%';$('#profileProgress').style.width=pct+'%';const badges=[['Pump Explorer','⚙️',pct>10],['Valve Learner','🚰',pct>25],['Process Builder','🏭',pct>40],['Reliability Champion','🛡️',pct>65],['Knowledge Leader','🏆',pct>85]];$('#badgeGrid').innerHTML=badges.map(b=>`<div class="card badge-card ${b[2]?'earned':'locked'}"><span>${b[1]}</span><b>${b[0]}</b><small>${b[2]?'Earned':'Locked'}</small></div>`).join('');}
function renderAdmin(){ $('#adminPanel').classList.toggle('hidden',!state.admin);$('#login').classList.toggle('hidden',state.admin); $('#aResources').textContent=state.resources.length; $('#aVideos').textContent=state.resources.filter(r=>r.type==='Video').length; $('#aDocs').textContent=state.resources.filter(r=>['Manual','Document','Case Study'].includes(r.type)).length; $('#lessonEquipment').innerHTML=equipment.map(e=>`<option value="${e.id}">${name(e)}</option>`).join(''); $('#adminContentList').innerHTML=state.resources.map(r=>`<div class="card admin-item"><div><b>${r.title}</b><p>${r.type} • ${name(equipment.find(e=>e.id===r.eq)||{})}</p></div><div><button onclick="editResource('${r.id}')">Edit</button><button class="danger" onclick="deleteResource('${r.id}')">Delete</button></div></div>`).join('');}
function resourceCard(r){let e=equipment.find(x=>x.id===r.eq);let done=state.completed.includes(r.id);return `<article class="card resource" onclick="openResource('${r.id}')"><span class="type">${r.type}</span><h3>${r.title}</h3><p>${r.desc}</p><small>${e?e.icon+' '+name(e):''}</small><button class="done ${done?'earned':''}" onclick="event.stopPropagation();toggleComplete('${r.id}')">${done?'Completed':'Mark Complete'}</button></article>`}
function list(title,arr){return `<section class="detail-section"><h3>${title}</h3><ul>${arr.map(x=>`<li>${x}</li>`).join('')}</ul></section>`}
function openEquipment(id){let e=equipment.find(x=>x.id===id);if(!e)return;openPage('equipmentDetail');$('#equipmentDetailBox').innerHTML=`<div class="detail-hero card"><div><span class="bigicon">${e.icon}</span><h1>${name(e)}</h1><p>${e.overview}</p><button class="primary" onclick="openPage('ai')">${T('ask')}</button></div><div class="model">${e.icon}<span>Digital Twin Placeholder</span><small>Interactive components in future sprint</small></div></div><div class="detail-grid">${list(T('components'),e.components)}${list(T('principle'),[e.principle])}${list(T('failures'),e.failures)}${list(T('troubleshooting'),e.troubleshooting)}${list(T('maintenance'),e.maintenance)}</div><h2>${T('resources')}</h2><div class="grid">${state.resources.filter(r=>r.eq===id).map(resourceCard).join('')||'<div class="card">No resources yet.</div>'}</div>`}
function openResource(id){let r=state.resources.find(x=>x.id===id);if(!r)return;let e=equipment.find(x=>x.id===r.eq);$('#dialogBody').innerHTML=`<h1>${r.title}</h1><p>${r.desc}</p><div class="video">${r.url?`<a href="${r.url}" target="_blank">Open ${r.type}</a>`:'▶ Resource Placeholder'}</div><p><b>Equipment:</b> ${e?name(e):''}</p><button class="primary" onclick="toggleComplete('${r.id}');document.getElementById('contentDialog').close()">Mark Complete</button>`;$('#contentDialog').showModal()}
function toggleComplete(id){state.completed=state.completed.includes(id)?state.completed.filter(x=>x!==id):[...state.completed,id];save();render()}
function editResource(id){let r=state.resources.find(x=>x.id===id);if(!r)return;openPage('admin');$('#editId').value=r.id;$('#lessonTitle').value=r.title;$('#lessonEquipment').value=r.eq;$('#lessonType').value=r.type;$('#lessonUrl').value=r.url||'';$('#lessonDesc').value=r.desc;scrollTo({top:0,behavior:'smooth'})}
function deleteResource(id){if(confirm('Delete?')){state.resources=state.resources.filter(r=>r.id!==id);save();render()}}
function askAI(q){q=q.trim(); if(!q)return; const lower=q.toLowerCase(); let answer='FALTAH prototype answer: This topic is available in the Knowledge Library. Try searching related equipment or resource titles.'; if(lower.includes('cavitation')) answer='Cavitation occurs when suction pressure drops below vapor pressure. Vapor bubbles form and collapse, causing noise, vibration and impeller damage. Review pump NPSH and suction conditions.'; else if(lower.includes('psv')) answer='A PSV opens when pressure reaches its set pressure to protect equipment from overpressure. Ensure the inlet/outlet path is available and inspection/calibration are current.'; else if(lower.includes('gate')||lower.includes('globe')) answer='Gate valves are mainly for isolation. Globe valves are better for throttling because their flow path supports control but creates higher pressure drop.'; else if(lower.includes('separator')) answer='A three-phase separator uses gravity and retention time to separate gas, oil and water. Stable level/interface control is critical.'; $('#aiChat').innerHTML+=`<div class="bubble user">${q}</div><div class="bubble bot">${answer}</div>`; $('#aiChat').scrollTop=$('#aiChat').scrollHeight; $('#aiInput').value='';}
window.openEquipment=openEquipment;window.openResource=openResource;window.editResource=editResource;window.deleteResource=deleteResource;window.toggleComplete=toggleComplete;window.openPage=openPage;
setTimeout(()=>$('#splash').classList.add('hide'),900); if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{}); apply();
document.addEventListener('click',e=>{let n=e.target.closest('[data-page]');if(n)openPage(n.dataset.page);let j=e.target.closest('[data-jump]');if(j)openPage(j.dataset.jump);let d=e.target.closest('[data-disc]');if(d){state.disc=d.dataset.disc;render()}let rt=e.target.closest('[data-rtype]');if(rt){state.rtype=rt.dataset.rtype;render()}let ans=e.target.closest('[data-answer]');if(ans){$('#challengeResult').textContent=ans.dataset.answer==='correct'?'✅ Correct! You earned challenge points.':'❌ Not correct. Review Pump Cavitation in the library.'}let q=e.target.closest('[data-question]');if(q)askAI(q.dataset.question);});
$('#langBtn').onclick=()=>{state.lang=state.lang==='en'?'ar':'en';localStorage.lang=state.lang;apply()}; $('#themeBtn').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';localStorage.theme=state.theme;apply()};
$('#equipmentSearch').oninput=e=>{state.q=e.target.value;render()}; $('#librarySearch').oninput=e=>{state.rq=e.target.value;render()}; $('#backExplorer').onclick=()=>openPage('explorer'); $('#closeDialog').onclick=()=>$('#contentDialog').close();
$('#adminLoginBtn').onclick=()=>{if($('#adminPass').value==='faltah'){state.admin=true;sessionStorage.admin='true';render()}else alert('Wrong password')}; $('#logout').onclick=()=>{state.admin=false;sessionStorage.removeItem('admin');render()};
$('#clearForm').onclick=()=>$('#contentForm').reset(); $('#contentForm').onsubmit=e=>{e.preventDefault();let id=$('#editId').value||'r'+Date.now();let r={id,title:$('#lessonTitle').value,eq:$('#lessonEquipment').value,type:$('#lessonType').value,url:$('#lessonUrl').value,desc:$('#lessonDesc').value};let i=state.resources.findIndex(x=>x.id===id);if(i>-1)state.resources[i]=r;else state.resources.unshift(r);save();e.target.reset();render()};
$('#aiAsk').onclick=()=>askAI($('#aiInput').value); $('#aiInput').addEventListener('keydown',e=>{if(e.key==='Enter')askAI(e.target.value)});
