const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const fallbackLessons=[
{id:'pump-basics',title:'Centrifugal Pump Fundamentals',equipment:'Centrifugal Pump',category:'Rotating Equipment',summary:'Explains impeller action, volute casing, NPSH, cavitation and minimum flow.',smartAnswer:'Low pump discharge pressure may be caused by low suction pressure, blocked suction strainer, air ingress, worn impeller, wrong rotation, or partially closed valves.',duration:'05:00',provider:'Rotating Equipment SME',videoUrl:'videos/sample-pump.mp4',documents:['documents/sample-pump-sop.pdf'],keywords:['pump','centrifugal','discharge pressure','cavitation','npsh','impeller'],featured:true},
{id:'control-valve',title:'Control Valve Basics',equipment:'Control Valve',category:'Valves',summary:'Explains how control valves regulate flow, pressure, level or temperature through actuator movement.',smartAnswer:'Control valves regulate process variables by changing valve opening in response to a controller signal. Common issues include sticking, air supply failure, positioner malfunction, incorrect tuning, and actuator problems.',duration:'04:00',provider:'Instrument SME',videoUrl:'videos/control-valve-basics.mp4',documents:['documents/control-valve-guide.pdf'],keywords:['control valve','positioner','actuator','flow control','valve'],featured:true},
{id:'separator',title:'Three Phase Separator',equipment:'Three Phase Separator',category:'Process Systems',summary:'Explains how gas, oil and water separate inside a vessel through gravity and level control.',smartAnswer:'A three-phase separator uses gravity to split gas, oil and water. Stable separation depends on inlet momentum reduction, residence time, interface control, mist extraction, and correct outlet control.',duration:'04:30',provider:'Process SME',videoUrl:'videos/separator.mp4',documents:['documents/separator-overview.pdf'],keywords:['separator','gas','oil','water','interface level'],featured:true}
];
let lessons=loadLessons(); let icons=loadIcons();
function loadLessons(){try{return JSON.parse(localStorage.getItem('faltah_cms_lessons_preview')||'null') || fallbackLessons}catch{return fallbackLessons}}
function loadIcons(){try{return JSON.parse(localStorage.getItem('faltah_cms_equipment_icons_preview')||'{}')}catch{return {}}}
function saveAll(){localStorage.setItem('faltah_cms_lessons_preview',JSON.stringify(lessons));localStorage.setItem('faltah_cms_equipment_icons_preview',JSON.stringify(icons));render();status('Saved locally. Open the main FALTAH page and press Sync Content to preview.');}
function uid(title){return (title||'lesson').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')+'-'+Date.now().toString().slice(-5)}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function splitList(v){return (v||'').split(',').map(x=>x.trim()).filter(Boolean)}
function status(msg){$('#statusBox').textContent=msg}
function render(){
  const eq=[...new Set(lessons.map(l=>l.equipment).filter(Boolean))];
  const docs=lessons.reduce((a,l)=>a+(l.documents?.length||0),0);
  $('#cmsStats').innerHTML=[['Equipment',eq.length],['Lessons',lessons.length],['Videos',lessons.filter(l=>l.videoUrl).length],['Documents',docs]].map(x=>`<div><b>${x[1]}</b><span>${x[0]}</span></div>`).join('');
  $('#lessonList').innerHTML=lessons.map(l=>`<div class="cms-item"><div><b>${esc(l.title)}</b><p>${esc(l.equipment||'')} • ${esc(l.category||'')} • ${esc(l.duration||'')}</p></div><div><button data-edit="${l.id}">Edit</button><button class="danger" data-delete="${l.id}">Delete</button></div></div>`).join('') || '<p>No lessons yet.</p>';
  $('#iconList').innerHTML=Object.entries(icons).map(([k,v])=>`<div class="cms-item"><div><b>${esc(k)}</b><p>${esc(v)}</p></div><button class="danger" data-delicon="${esc(k)}">Delete</button></div>`).join('') || '<p class="hint">No custom icons yet.</p>';
}
function clearForm(){$('#lessonId').value='';$('#title').value='';$('#equipment').value='';$('#category').value='Process Systems';$('#duration').value='';$('#provider').value='';$('#videoUrl').value='';$('#documents').value='';$('#keywords').value='';$('#summary').value='';$('#smartAnswer').value='';$('#featured').checked=false;}
function fillLesson(id){const l=lessons.find(x=>x.id===id); if(!l)return; $('#lessonId').value=l.id; $('#title').value=l.title||''; $('#equipment').value=l.equipment||''; $('#category').value=l.category||'Process Systems'; $('#duration').value=l.duration||''; $('#provider').value=l.provider||''; $('#videoUrl').value=l.videoUrl||''; $('#documents').value=(l.documents||[]).join(', '); $('#keywords').value=(l.keywords||[]).join(', '); $('#summary').value=l.summary||''; $('#smartAnswer').value=l.smartAnswer||''; $('#featured').checked=!!l.featured; window.scrollTo({top:0,behavior:'smooth'});}
function downloadJson(name,obj){const blob=new Blob([JSON.stringify(obj,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
$('#saveLesson').onclick=()=>{const item={id:$('#lessonId').value||uid($('#title').value),title:$('#title').value,equipment:$('#equipment').value,category:$('#category').value,summary:$('#summary').value,smartAnswer:$('#smartAnswer').value,duration:$('#duration').value,provider:$('#provider').value,videoUrl:$('#videoUrl').value,documents:splitList($('#documents').value),keywords:splitList($('#keywords').value),featured:$('#featured').checked}; if(!item.title){alert('Lesson title is required');return} const i=lessons.findIndex(l=>l.id===item.id); if(i>=0) lessons[i]=item; else lessons.unshift(item); saveAll(); clearForm();};
$('#resetForm').onclick=clearForm;
$('#saveIcon').onclick=()=>{const eq=$('#iconEquipment').value.trim(), val=$('#iconValue').value.trim(); if(!eq||!val){alert('Equipment name and icon are required');return} icons[eq]=val; saveAll(); $('#iconEquipment').value=''; $('#iconValue').value='';};
$('#clearIcon').onclick=()=>{$('#iconEquipment').value='';$('#iconValue').value='';};
$('#exportLessons').onclick=()=>downloadJson('lessons.json',lessons);
$('#exportIcons').onclick=()=>downloadJson('equipment-icons.json',icons);
$('#clearPreview').onclick=()=>{if(confirm('Clear local CMS preview and return to starter data?')){localStorage.removeItem('faltah_cms_lessons_preview');localStorage.removeItem('faltah_cms_equipment_icons_preview');lessons=fallbackLessons;icons={};render();status('Local preview cleared.')}};
$('#importLessons').onchange=e=>{const f=e.target.files[0]; if(!f)return; const r=new FileReader(); r.onload=()=>{try{lessons=JSON.parse(r.result);saveAll();status('Imported lessons.json successfully.')}catch{alert('Invalid JSON file')}}; r.readAsText(f);};
$('#importIcons').onchange=e=>{const f=e.target.files[0]; if(!f)return; const r=new FileReader(); r.onload=()=>{try{icons=JSON.parse(r.result);saveAll();status('Imported equipment-icons.json successfully.')}catch{alert('Invalid JSON file')}}; r.readAsText(f);};
document.addEventListener('click',e=>{const edit=e.target.closest('[data-edit]'); if(edit)fillLesson(edit.dataset.edit); const del=e.target.closest('[data-delete]'); if(del&&confirm('Delete lesson?')){lessons=lessons.filter(l=>l.id!==del.dataset.delete);saveAll();} const delicon=e.target.closest('[data-delicon]'); if(delicon&&confirm('Delete icon?')){delete icons[delicon.dataset.delicon];saveAll();}});
render();
